/*
 * Copyright (c) eHealth
 */
package be.jeremy.pascal.ci.backend;

import be.jeremy.pascal.ci.intermediate.ICode;
import be.jeremy.pascal.ci.intermediate.SymTab;
import be.jeremy.pascal.ci.message.MessageHandler;
import be.jeremy.pascal.ci.message.MessageProducer;

/**
 * @author Jeremy Vanpe (eh056)
 */
public abstract class Backend implements MessageProducer {

    protected static MessageHandler messageHandler = new MessageHandler();

    protected SymTab symTab;
    protected ICode iCode;

    /**
     * Process the intermediate code and the symbol table generated by the
     * parser.  To be implemented by a compiler or an interpreter subclass.
     *
     * @param iCode  the intermediate code.
     * @param symTab the symbol table.
     * @throws Exception if an error occurred.
     */
    public abstract void process(ICode iCode, SymTab symTab) throws Exception;

}

